/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WidgetMode, WidgetPositionX, WidgetPositionY, WidgetStatus, WidgetVariant } from "./components/staylift-widget/staylift-widget";
export { WidgetMode, WidgetPositionX, WidgetPositionY, WidgetStatus, WidgetVariant } from "./components/staylift-widget/staylift-widget";
export namespace Components {
    interface StayliftOrb {
        /**
          * @default 0
         */
        "inputVolume": number;
        /**
          * @default false
         */
        "isActive": boolean;
        /**
          * @default 0
         */
        "outputVolume": number;
        /**
          * @default '#6366f1'
         */
        "primaryColor"?: string;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | number;
    }
    interface StayliftWidget {
        "agentId": string;
        /**
          * @default false
         */
        "autoExpand": boolean;
        "avatarUrl"?: string;
        /**
          * @default 'Customer Support'
         */
        "brandName": string;
        "endConversation": () => Promise<void>;
        /**
          * @default 'Start'
         */
        "fabButtonText": string;
        /**
          * @default 'Do you need help?'
         */
        "fabPrompt": string;
        "getStatus": () => Promise<WidgetStatus>;
        /**
          * @default 'en'
         */
        "language": string;
        /**
          * @default 'dark'
         */
        "mode": WidgetMode;
        /**
          * @default 'right'
         */
        "positionX": WidgetPositionX;
        /**
          * @default 'bottom'
         */
        "positionY": WidgetPositionY;
        /**
          * @default '#6366f1'
         */
        "primaryColor": string;
        "sendMessage": (text: string) => Promise<void>;
        /**
          * @default true
         */
        "showBranding": boolean;
        "startConversation": (textOnly?: boolean) => Promise<void>;
        /**
          * @default 'floating'
         */
        "variant": WidgetVariant;
    }
}
export interface StayliftWidgetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStayliftWidgetElement;
}
declare global {
    interface HTMLStayliftOrbElement extends Components.StayliftOrb, HTMLStencilElement {
    }
    var HTMLStayliftOrbElement: {
        prototype: HTMLStayliftOrbElement;
        new (): HTMLStayliftOrbElement;
    };
    interface HTMLStayliftWidgetElementEventMap {
        "conversationStarted": void;
        "conversationEnded": void;
        "widgetError": { message: string; code?: string };
        "statusChanged": WidgetStatus;
        "messageReceived": ChatMessage;
    }
    interface HTMLStayliftWidgetElement extends Components.StayliftWidget, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStayliftWidgetElementEventMap>(type: K, listener: (this: HTMLStayliftWidgetElement, ev: StayliftWidgetCustomEvent<HTMLStayliftWidgetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStayliftWidgetElementEventMap>(type: K, listener: (this: HTMLStayliftWidgetElement, ev: StayliftWidgetCustomEvent<HTMLStayliftWidgetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStayliftWidgetElement: {
        prototype: HTMLStayliftWidgetElement;
        new (): HTMLStayliftWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "staylift-orb": HTMLStayliftOrbElement;
        "staylift-widget": HTMLStayliftWidgetElement;
    }
}
declare namespace LocalJSX {
    interface StayliftOrb {
        /**
          * @default 0
         */
        "inputVolume"?: number;
        /**
          * @default false
         */
        "isActive"?: boolean;
        /**
          * @default 0
         */
        "outputVolume"?: number;
        /**
          * @default '#6366f1'
         */
        "primaryColor"?: string;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | number;
    }
    interface StayliftWidget {
        "agentId": string;
        /**
          * @default false
         */
        "autoExpand"?: boolean;
        "avatarUrl"?: string;
        /**
          * @default 'Customer Support'
         */
        "brandName"?: string;
        /**
          * @default 'Start'
         */
        "fabButtonText"?: string;
        /**
          * @default 'Do you need help?'
         */
        "fabPrompt"?: string;
        /**
          * @default 'en'
         */
        "language"?: string;
        /**
          * @default 'dark'
         */
        "mode"?: WidgetMode;
        "onConversationEnded"?: (event: StayliftWidgetCustomEvent<void>) => void;
        "onConversationStarted"?: (event: StayliftWidgetCustomEvent<void>) => void;
        "onMessageReceived"?: (event: StayliftWidgetCustomEvent<ChatMessage>) => void;
        "onStatusChanged"?: (event: StayliftWidgetCustomEvent<WidgetStatus>) => void;
        "onWidgetError"?: (event: StayliftWidgetCustomEvent<{ message: string; code?: string }>) => void;
        /**
          * @default 'right'
         */
        "positionX"?: WidgetPositionX;
        /**
          * @default 'bottom'
         */
        "positionY"?: WidgetPositionY;
        /**
          * @default '#6366f1'
         */
        "primaryColor"?: string;
        /**
          * @default true
         */
        "showBranding"?: boolean;
        /**
          * @default 'floating'
         */
        "variant"?: WidgetVariant;
    }
    interface IntrinsicElements {
        "staylift-orb": StayliftOrb;
        "staylift-widget": StayliftWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "staylift-orb": LocalJSX.StayliftOrb & JSXBase.HTMLAttributes<HTMLStayliftOrbElement>;
            "staylift-widget": LocalJSX.StayliftWidget & JSXBase.HTMLAttributes<HTMLStayliftWidgetElement>;
        }
    }
}
